### ISSUE TITLE
New feature suggestion to the `anomaly` function (code included)

### ISSUE THREAD

**Issue by DavidArenburg** [robjhyndman/anomalous#5]
Hi,

Very nice package, thank you.

Though, I feel like this package could use another small feature. The `n` parameter in the `anomaly` function basically returns `n` most "anomalous" time-series, while we can basically return them all (if `n` == `nrow(x)`). In other words, we don't have some significance measure that will tell us how significantly anomalous those series are and we can't specify our desired significance threshold (in other words, we don't know how to specify `n` correctly).

I've took a look in the [anomaly function source code](https://github.com/robjhyndman/anomalous/blob/master/R/detect_outliers.R) and saw that this is already being calculated using the `hdrcde::hdr.2d` function and it could pretty easily be incorporated into the `anomaly` function.

I don't know if this is really makes sense, so I haven't made it a PR. Instead, I've made a [GIST](https://gist.github.com/DavidArenburg/fd56948c9ba9f409570c6438e64a326d) that adds a parameter called `sig`. If speciffied, it will return/plot the time series that are `sig <= hdrinfo$falpha` . I've also tried to make sure that it is backward compatible and won't brake any existing code.

Please advise,
Thanks again,
David

**Comment by robjhyndman** [comment]
That looks good to me. Feel free to make a PR

**Comment by DavidArenburg** [comment]
I've gave it another thought and I'm not sure anymore that my addition does what I meant. It just basically returns a quantile without any significance check. Meaning, there is no real indication that these series have anomalies, instead, they just have the lowest density. In theory, if neither of the series had anomalies, it will still return the same number of series. 

What I was looking for is to make something equivalent to a t-test that will test the hypothesis (with the specified significance level) that the series is anomalous or not, but I guess it's not so simple as we can't really make any assumptions on the distribution.

**Comment by robjhyndman** [comment]
It is really hard to define what anomalous means. The stray package by my student Dilini Talagala (https://github.com/pridiltal/stray) uses extreme value theory to do it and it works pretty well. If I was solving this problem now, I would use the tsfeatures package combined with the stray package.

**Comment by DavidArenburg** [comment]
OK, thanks for your time, I'll take a look. 

As a side note (truly, no pun intended), it's too bad he made such a huge number of huge dependencies (such as `tidyverse`) only in order to use two functions `purrr::flatten` (`unlist`?) and `dplyr::mutate` (`$`?). 

I'm going to make a lightweight/vectorized version of that package in order to test it.

Thanks again for your time and great work.

**Comment by robjhyndman** [comment]
Good point. Feel free to send her a PR or comment about how to reduce the dependencies.
